services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.watermark.low=99%
      - cluster.routing.allocation.disk.watermark.high=99%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
    volumes:
      - ./data/bitnami/elasticsearch:/usr/share/elasticsearch/data
      - ./volumes/elasticsearch/analysis-smartcn.zip:/tmp/analysis-smartcn.zip:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:9200 && [ -f /tmp/es_plugins_ready ]',
        ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s
    user: "1000:1000"
    command: >
      bash -c "
        if [ ! -d /usr/share/elasticsearch/plugins/analysis-smartcn ]; then
          echo 'Installing smartcn plugin...';
          elasticsearch-plugin install file:///tmp/analysis-smartcn.zip;
        fi;
        touch /tmp/es_plugins_ready;
        echo 'Plugin ready';
        exec /usr/local/bin/docker-entrypoint.sh elasticsearch
      "

  redis:
    image: redis:8.0
    command: redis-server --appendonly no --port ${REDIS_PORT_NUMBER:-6379}
    volumes:
      - ./data/bitnami/redis:/data:rw,Z

  etcd:
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=default=http://0.0.0.0:2380
    volumes:
      - ./data/bitnami/etcd:/etcd-data:rw,Z
    command: etcd --data-dir=/etcd-data
