apiVersion: v1
kind: Service
metadata:
  name: rocketmq-console
  namespace: rocketmq
  labels:
    app: rocketmq
    component: console
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080  # 可以通过节点IP:30080访问管理界面
      protocol: TCP
  selector:
    app: rocketmq
    component: console