apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq
  labels:
    app: rocketmq
    component: namesrv
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 9876
      targetPort: 9876
      protocol: TCP
  selector:
    app: rocketmq
    component: namesrv